### ISSUE TITLE
Can not restore database backup made with Old version of Financisto

### ISSUE THREAD

**Issue by babetoduarte** [BlueCatMe/financisto#6]
When I tried to migrate a backup database from my OLD financisto app (1.8?) into Financisto+, the import window doesn't show the available '.backup' file generated by my old configuration.

Here's a screenshot of the .backup file in the root of the Financisto+ folder:
![Screenshot_20220523-110000](https://user-images.githubusercontent.com/2272956/169860772-5a15a494-f31c-448a-a892-1909c4218edb.png)

Here, when I try to load that file, I can only see a trash file of a previous backup I deleted, generated by Financisto+:
![Screenshot_20220523-110032](https://user-images.githubusercontent.com/2272956/169860774-5d9037c2-cbb8-4015-a285-234b461c5d1f.png)
.

**Comment by kaminoji** [comment]
https://github.com/BlueCatMe/financisto#restore-from-the-orignal-finicisto

**Comment by babetoduarte** [comment]
@kaminoji thanks for pointing this out.. my bad for not reading the readme instructions in the first place. I did the procedure as described using ADB, and it worked like a charm! 

I guess this is how data should be migrated, and therefore not a real issue with Financisto+ itself, thus this issue should be closed.
